# Generated by Django 5.1.3 on 2024-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='product', to='app.category'),
        ),
    ]
